package com.json.rick_morty.presentation.view.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006971)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF82F3FF)
val md_theme_light_onPrimaryContainer = Color(0xFF002022)
val md_theme_light_secondary = Color(0xFF785A00)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDF9C)
val md_theme_light_onSecondaryContainer = Color(0xFF251A00)
val md_theme_light_tertiary = Color(0xFF984719)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDBCC)
val md_theme_light_onTertiaryContainer = Color(0xFF351000)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF2D1600)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF2D1600)
val md_theme_light_surfaceVariant = Color(0xFFDAE4E5)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4849)
val md_theme_light_outline = Color(0xFF6F797A)
val md_theme_light_inverseOnSurface = Color(0xFFFFEEE1)
val md_theme_light_inverseSurface = Color(0xFF4B2800)
val md_theme_light_inversePrimary = Color(0xFF4DD9E6)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006971)
val md_theme_light_outlineVariant = Color(0xFFBEC8C9)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF4DD9E6)
val md_theme_dark_onPrimary = Color(0xFF00363B)
val md_theme_dark_primaryContainer = Color(0xFF004F55)
val md_theme_dark_onPrimaryContainer = Color(0xFF82F3FF)
val md_theme_dark_secondary = Color(0xFFF8BE1C)
val md_theme_dark_onSecondary = Color(0xFF3F2E00)
val md_theme_dark_secondaryContainer = Color(0xFF5B4300)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDF9C)
val md_theme_dark_tertiary = Color(0xFFFFB693)
val md_theme_dark_onTertiary = Color(0xFF561F00)
val md_theme_dark_tertiaryContainer = Color(0xFF7A3001)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDBCC)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF2D1600)
val md_theme_dark_onBackground = Color(0xFFFFDCC0)
val md_theme_dark_surface = Color(0xFF2D1600)
val md_theme_dark_onSurface = Color(0xFFFFDCC0)
val md_theme_dark_surfaceVariant = Color(0xFF3F4849)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC8C9)
val md_theme_dark_outline = Color(0xFF899294)
val md_theme_dark_inverseOnSurface = Color(0xFF2D1600)
val md_theme_dark_inverseSurface = Color(0xFFFFDCC0)
val md_theme_dark_inversePrimary = Color(0xFF006971)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF4DD9E6)
val md_theme_dark_outlineVariant = Color(0xFF3F4849)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF62A4AB)
